[build]
builder = "DOCKERFILE"
dockerfilePath = "src/main/docker/Dockerfile.native"

[deploy]
startCommand = "/bin/sh -c './zamhealth -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=$PORT'"
healthcheckPath = "/q/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3